import { useEffect, useState } from 'react';
import { CalendarPlus, ChevronRight, ClipboardPlus, FileChartColumn, HeartPulse, Pill, Search, Stethoscope } from 'lucide-react';
import { useNavigate } from 'umi';
import { BottomTab } from '../../components/BottomTab';
import { Dialog } from '../../components/Dialog';
import { getSelection, saveSelection } from '../../models/selection';
import { getFamilyMembers } from '../../services/family';
import { getAppointments, getHospitals } from '../../services/registration';
import type { FamilyMember, Hospital } from '../../typings/api';
import { formatMedicalTime, sortHospitals } from '../../utils/medical';

/** 展示医院入口、就诊人、快捷服务和健康待办的首页。 */
export default function HomePage() {
  const navigate = useNavigate(); const [hospitals, setHospitals] = useState<Hospital[]>([]); const [members, setMembers] = useState<FamilyMember[]>([]); const [selected, setSelected] = useState(getSelection()); const [patientOpen, setPatientOpen] = useState(false); const [notice, setNotice] = useState(''); const [appointments, setAppointments] = useState<any[]>([]);
  /** 初始化首页所需的医院、就诊人和待办订单。 */
  async function loadHome() { try { const [nextHospitals, nextMembers] = await Promise.all([getHospitals(), getFamilyMembers()]); setHospitals(sortHospitals(nextHospitals)); setMembers(nextMembers); const state = getSelection(); const next = { hospitalId: state.hospitalId || nextHospitals[0]?.hospitalId, patientId: state.patientId || nextMembers.find((item) => item.isDefault)?.patientId || nextMembers[0]?.patientId }; saveSelection(next); setSelected(next); if (next.patientId) setAppointments((await getAppointments(next.patientId)).records); } catch (error: any) { setNotice(error.message || '首页数据加载失败'); } }
  useEffect(() => { void loadHome(); }, []);
  const currentHospital = hospitals.find((item) => item.hospitalId === selected.hospitalId); const currentPatient = members.find((item) => item.patientId === selected.patientId);
  return <main className="home-page"><header className="home-hero"><div className="home-brand"><b>智</b><div><strong>智愈先锋</strong><span>省人民医院智慧医疗服务</span></div></div><p>让每一次就医，都更清晰、更安心</p></header><section className="home-content"><button className="hospital-switch" type="button" onClick={() => navigate('/home/hospitals')}>当前医院：{currentHospital?.name || '选择医院'} <ChevronRight size={18} /></button><button className="search-bar" type="button" onClick={() => navigate('/home/departments')}><Search size={24} /><span>搜索医生、科室</span></button><section className="patient-switch-card"><div><b>当前就诊人 · {currentPatient?.name || '未选择'}</b><p>{currentPatient?.phone || '资料待完善'}</p></div><button type="button" className="text-button" onClick={() => setPatientOpen(true)}>切换 <ChevronRight size={19} /></button></section><h2>快捷服务</h2><section className="quick-grid">{[{ label: '预约挂号', icon: CalendarPlus, action: () => navigate('/home/departments') }, { label: '智能导诊', icon: Stethoscope, action: () => navigate('/agent', { state: { from: '/home' } }) }, { label: '在线问诊', icon: HeartPulse, action: () => navigate('/assistant') }, { label: '处方购药', icon: Pill }, { label: '报告查询', icon: FileChartColumn }, { label: '用药提醒', icon: ClipboardPlus }].map(({ label, icon: Icon, action }) => <button key={label} type="button" onClick={action || (() => setNotice(`${label}暂未开放`))}><Icon size={29} /><span>{label}</span></button>)}</section><section className="todo-section"><h2>健康待办</h2>{appointments.filter((item) => item.status === 'UNPAID' || item.status === 'PAID').slice(0, 2).map((item) => <button className="todo-item" type="button" key={item.id} onClick={() => navigate('/assistant')}><b>{formatMedicalTime(item.startTime)} · {item.departmentName}</b><span>{item.doctorName} · {item.status === 'UNPAID' ? '待支付' : '待就诊'}</span></button>)}{!appointments.length && <p className="empty-state">暂无健康待办</p>}</section></section>{patientOpen && <Dialog title="切换就诊人" onClose={() => setPatientOpen(false)}>{members.map((item) => <button className="choice-row" key={item.patientId} type="button" onClick={() => { saveSelection({ patientId: item.patientId }); setSelected(getSelection()); setPatientOpen(false); void loadHome(); }}>{item.name}<small>{item.relationName || item.relation}</small></button>)}{members.filter((item) => item.relation !== 'SELF').length === 0 && <p className="empty-state">当前用户未绑定亲属</p>}</Dialog>}{notice && <div className="toast" onClick={() => setNotice('')}>{notice}</div>}<BottomTab onUnavailable={() => setNotice('该页面暂未开放')} /></main>;
}
