import { useEffect, useRef, useState } from 'react';
import { Send } from 'lucide-react';
import { useParams } from 'umi';
import { PageHeader } from '../../components/PageHeader';
import { getConsultation, sendConsultationMessage } from '../../services/consultation';
import type { ConsultationDetail } from '../../typings/api';
import { createIdempotencyKey, getApiErrorMessage } from '../../utils/form';

/** 渲染问诊文字消息，并仅在接诊中允许患者发送。 */
export default function ConsultationPage() { const { consultationId } = useParams(); const [detail, setDetail] = useState<ConsultationDetail>(); const [content, setContent] = useState(''); const [notice, setNotice] = useState(''); const key = useRef<string>(); const load = async () => { try { setDetail(await getConsultation(Number(consultationId))); } catch (error) { setNotice(getApiErrorMessage(error)); } }; useEffect(() => { void load(); }, [consultationId]); async function send() { if (!content.trim() || detail?.status !== 'IN_PROGRESS') return; try { await sendConsultationMessage(Number(consultationId), content.trim(), key.current || (key.current = createIdempotencyKey())); key.current = undefined; setContent(''); await load(); } catch (error) { setNotice(getApiErrorMessage(error)); await load(); } } const editable = detail?.status === 'IN_PROGRESS'; return <main className="subpage"><PageHeader title="在线问诊" /><section className="subpage-content chat-page"><h2>{detail?.doctor.name || '医生问诊'}</h2><p>{detail?.status === 'PENDING' ? '等待医生接诊' : detail?.status === 'COMPLETED' || detail?.status === 'NO_SHOW' ? '本次问诊已结束' : '医生正在接诊'}</p><div className="chat-list">{detail?.messages.map((item) => <p className={item.senderType === 'PATIENT' ? 'mine-message' : 'doctor-message'} key={item.id}>{item.content}</p>)}</div><div className="chat-input"><textarea disabled={!editable} value={content} maxLength={2000} placeholder={editable ? '输入要咨询的问题' : '当前状态不可发送消息'} onChange={(event) => setContent(event.target.value)} /><button type="button" disabled={!editable} aria-label="发送消息" onClick={() => void send()}><Send size={20} /></button></div></section>{notice && <div className="toast" onClick={() => setNotice('')}>{notice}</div>}</main>; }
