import { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'umi';
import { PageHeader } from '../../components/PageHeader';
import { cancelAppointment, getPayment, simulatePayment } from '../../services/registration';
import { createIdempotencyKey, getApiErrorMessage } from '../../utils/form';
import { formatAmount, getRemainingSeconds } from '../../utils/medical';

/** 展示支付状态、倒计时并执行模拟支付。 */
export default function PaymentPage() { const { paymentId } = useParams(); const navigate = useNavigate(); const appointmentId = Number(new URLSearchParams(location.search).get('appointmentId')); const [payment, setPayment] = useState<any>(); const [password, setPassword] = useState(''); const [seconds, setSeconds] = useState(0); const [notice, setNotice] = useState(''); const key = useRef<string>(); const load = async () => { try { const next = await getPayment(Number(paymentId)); setPayment(next); setSeconds(getRemainingSeconds(next.expireAt)); } catch (error) { setNotice(getApiErrorMessage(error)); } }; useEffect(() => { void load(); }, [paymentId]); useEffect(() => { const timer = window.setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, []); async function pay() { try { await simulatePayment(Number(paymentId), password, key.current || (key.current = createIdempotencyKey())); key.current = undefined; await load(); setNotice('支付成功'); } catch (error) { setNotice(getApiErrorMessage(error)); await load(); } } async function cancel() { try { await cancelAppointment(appointmentId, createIdempotencyKey()); navigate('/assistant'); } catch (error) { setNotice(getApiErrorMessage(error)); await load(); } } return <main className="subpage"><PageHeader title="挂号支付" /><section className="subpage-content payment-card"><h2>{payment?.status === 'SUCCESS' ? '支付成功' : '请完成支付'}</h2><b>{formatAmount(payment?.amountCent || 0)}</b><p>剩余支付时间：{String(Math.floor(seconds / 60)).padStart(2, '0')}:{String(seconds % 60).padStart(2, '0')}</p>{payment?.status === 'PENDING' && <><label>登录密码<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><button className="primary-button" type="button" onClick={() => void pay()}>确认支付</button><button className="secondary-button" type="button" onClick={() => void cancel()}>取消挂号</button></>}</section>{notice && <div className="toast" onClick={() => setNotice('')}>{notice}</div>}</main>; }
