-- 智愈先锋 C 端业务 PostgreSQL 建表脚本
-- 说明：本脚本仅创建 C 端业务表；updated_at 由 Spring Boot 应用层维护。

begin;
-- 说明：仅创建 C 端业务表；updated_at 由 Spring Boot 应用层维护。


-- C 端独立登录用户表
create table if not exists c_user (
                                      id bigint generated by default as identity primary key, -- 用户主键
                                      account varchar(32) not null, -- C 端登录账号
                                      password varchar(64) not null, -- 登录密码，仅限演示环境
                                      status varchar(20) not null default 'ACTIVE', -- 账号状态
                                      last_login_at timestamptz, -- 最近登录时间
                                      created_at timestamptz not null default now(), -- 创建时间
                                      updated_at timestamptz not null default now(), -- 更新时间
                                      deleted_at timestamptz, -- 软删除时间
                                      constraint uk_c_user_account unique (account),
                                      constraint ck_c_user_status check (status in ('ACTIVE', 'DISABLED'))
);
comment on table c_user is 'C端独立登录用户表，不与B端账号体系关联';

-- C 端刷新令牌会话表
create table if not exists c_refresh_token (
                                               id bigint generated by default as identity primary key, -- 会话主键
                                               user_id bigint not null references c_user(id), -- 所属C端用户
                                               token_hash varchar(128) not null, -- 刷新令牌哈希
                                               device_id varchar(128), -- 客户端设备标识
                                               expired_at timestamptz not null, -- 令牌过期时间
                                               revoked_at timestamptz, -- 令牌撤销时间
                                               created_at timestamptz not null default now(), -- 创建时间
                                               updated_at timestamptz not null default now(), -- 更新时间
                                               constraint uk_c_refresh_token_hash unique (token_hash)
);
create index if not exists idx_c_refresh_token_user on c_refresh_token(user_id, expired_at desc);
comment on table c_refresh_token is 'C端刷新令牌会话表';

-- 患者基础档案表
create table if not exists patient_profile (
                                               id bigint generated by default as identity primary key, -- 患者档案主键
                                               owner_user_id bigint not null references c_user(id), -- 管理该就诊人的C端账号
                                               relation varchar(16) not null default 'SELF', -- 与账号拥有者的关系
                                               active boolean not null default true, -- 是否可作为当前账号的就诊人
                                               name varchar(64), -- 患者姓名
                                               gender varchar(16), -- 性别
                                               birthday date, -- 出生日期
                                               phone varchar(20), -- 联系电话，仅限演示环境
                                               id_card_no varchar(32), -- 身份证号，仅限演示环境
                                               emergency_contact varchar(128), -- 紧急联系人信息
                                               created_at timestamptz not null default now(), -- 创建时间
                                               updated_at timestamptz not null default now(), -- 更新时间
                                               deleted_at timestamptz, -- 解绑后的软删除时间
                                               constraint ck_patient_profile_relation check (relation in ('SELF', 'SPOUSE', 'PARENT', 'CHILD', 'OTHER')),
                                               constraint ck_patient_profile_gender check (gender is null or gender in ('MALE', 'FEMALE', 'UNKNOWN'))
);
create index if not exists idx_patient_profile_owner_active on patient_profile(owner_user_id, active, created_at desc) where deleted_at is null;
create unique index if not exists uk_patient_profile_owner_self on patient_profile(owner_user_id) where relation = 'SELF' and active = true and deleted_at is null;
create unique index if not exists uk_patient_profile_owner_id_card on patient_profile(owner_user_id, id_card_no) where id_card_no is not null and active = true and deleted_at is null;
comment on table patient_profile is 'C端账号本人及家庭成员就诊人档案表';

-- 患者过敏史表
create table if not exists patient_allergy (
                                               id bigint generated by default as identity primary key, -- 过敏史主键
                                               patient_id bigint not null references patient_profile(id), -- 所属患者
                                               allergen varchar(128) not null, -- 过敏原
                                               reaction varchar(512), -- 过敏反应描述
                                               severity varchar(20), -- 严重程度
                                               created_at timestamptz not null default now(), -- 创建时间
                                               updated_at timestamptz not null default now(), -- 更新时间
                                               deleted_at timestamptz -- 软删除时间
);
create index if not exists idx_patient_allergy_patient on patient_allergy(patient_id) where deleted_at is null;
comment on table patient_allergy is '患者过敏史表';

-- 患者既往史表
create table if not exists patient_medical_history (
                                                       id bigint generated by default as identity primary key, -- 既往史主键
                                                       patient_id bigint not null references patient_profile(id), -- 所属患者
                                                       content varchar(1000) not null, -- 既往病史内容
                                                       occurred_at date, -- 病史发生日期
                                                       created_at timestamptz not null default now(), -- 创建时间
                                                       updated_at timestamptz not null default now(), -- 更新时间
                                                       deleted_at timestamptz -- 软删除时间
);
create index if not exists idx_patient_history_patient on patient_medical_history(patient_id) where deleted_at is null;
comment on table patient_medical_history is '患者既往病史表';

-- 导诊评估记录表
create table if not exists triage_assessment (
                                                 id bigint generated by default as identity primary key, -- 导诊评估主键
                                                 patient_id bigint not null references patient_profile(id), -- 发起评估的患者
                                                 symptom_input jsonb not null, -- 症状、病史和体温等输入快照
                                                 urgency varchar(20) not null, -- 紧急程度
                                                 recommended_departments jsonb not null default '[]'::jsonb, -- 推荐科室和理由快照
                                                 created_at timestamptz not null default now(), -- 创建时间
                                                 constraint ck_triage_assessment_urgency check (urgency in ('LOW', 'MEDIUM', 'HIGH'))
);
create index if not exists idx_triage_assessment_patient_created on triage_assessment(patient_id, created_at desc);
comment on table triage_assessment is '患者导诊评估记录表';

-- 医院科室表
create table if not exists department (
                                          id bigint generated by default as identity primary key, -- 科室主键
                                          parent_id bigint references department(id), -- 上级科室
                                          name varchar(64) not null, -- 科室名称
                                          code varchar(32) not null, -- 科室编码
                                          description varchar(500), -- 科室简介
                                          status varchar(20) not null default 'ENABLED', -- 启用状态
                                          sort_order integer not null default 0, -- 展示排序
                                          created_at timestamptz not null default now(), -- 创建时间
                                          updated_at timestamptz not null default now(), -- 更新时间
                                          deleted_at timestamptz, -- 软删除时间
                                          constraint uk_department_code unique (code),
                                          constraint ck_department_status check (status in ('ENABLED', 'DISABLED'))
);
create index if not exists idx_department_parent on department(parent_id, sort_order) where deleted_at is null;
comment on table department is '医院科室表';

-- 医生基础信息表
create table if not exists doctor (
                                      id bigint generated by default as identity primary key, -- 医生主键
                                      department_id bigint not null references department(id), -- 执业科室
                                      name varchar(64) not null, -- 医生姓名
                                      title varchar(64), -- 医生职称
                                      specialty varchar(1000), -- 擅长领域
                                      introduction varchar(2000), -- 医生简介
                                      registration_fee_cent integer not null default 0, -- 挂号费，单位分
                                      status varchar(20) not null default 'ENABLED', -- 出诊状态
                                      created_at timestamptz not null default now(), -- 创建时间
                                      updated_at timestamptz not null default now(), -- 更新时间
                                      deleted_at timestamptz, -- 软删除时间
                                      constraint ck_doctor_fee check (registration_fee_cent >= 0),
                                      constraint ck_doctor_status check (status in ('ENABLED', 'DISABLED', 'SUSPENDED'))
);
create index if not exists idx_doctor_department on doctor(department_id, status) where deleted_at is null;
comment on table doctor is '医生基础信息表';

-- 医生可预约号源时段表
create table if not exists schedule_slot (
                                             id bigint generated by default as identity primary key, -- 号源时段主键
                                             doctor_id bigint not null references doctor(id), -- 出诊医生
                                             start_time timestamptz not null, -- 时段开始时间
                                             end_time timestamptz not null, -- 时段结束时间
                                             total_count integer not null, -- 总号源数
                                             available_count integer not null, -- PostgreSQL最终一致性可约余量
                                             fee_cent integer not null, -- 当前时段挂号费，单位分
                                             status varchar(20) not null default 'OPEN', -- 时段状态
                                             created_at timestamptz not null default now(), -- 创建时间
                                             updated_at timestamptz not null default now(), -- 更新时间
                                             deleted_at timestamptz, -- 软删除时间
                                             constraint uk_schedule_slot unique (doctor_id, start_time),
                                             constraint ck_schedule_slot_time check (end_time > start_time),
                                             constraint ck_schedule_slot_count check (total_count >= 0 and available_count between 0 and total_count),
                                             constraint ck_schedule_slot_fee check (fee_cent >= 0),
                                             constraint ck_schedule_slot_status check (status in ('OPEN', 'CLOSED', 'SUSPENDED'))
);
create index if not exists idx_schedule_slot_doctor_time on schedule_slot(doctor_id, start_time) where deleted_at is null;
create index if not exists idx_schedule_slot_open_time on schedule_slot(status, start_time) where status = 'OPEN' and deleted_at is null;
comment on table schedule_slot is '医生可预约号源时段表';

-- 挂号订单表
create table if not exists appointment_order (
                                                 id bigint generated by default as identity primary key, -- 挂号订单主键
                                                 patient_id bigint not null references patient_profile(id), -- 就诊患者
                                                 slot_id bigint not null references schedule_slot(id), -- 预约号源时段
                                                 status varchar(20) not null, -- 挂号订单状态
                                                 amount_cent integer not null, -- 挂号金额，单位分
                                                 expire_at timestamptz, -- 锁号支付到期时间
                                                 paid_at timestamptz, -- 支付完成时间
                                                 cancelled_at timestamptz, -- 取消时间
                                                 created_at timestamptz not null default now(), -- 创建时间
                                                 updated_at timestamptz not null default now(), -- 更新时间
                                                 constraint ck_appointment_status check (status in ('LOCKED', 'PAID', 'CANCELLED', 'EXPIRED')),
                                                 constraint ck_appointment_amount check (amount_cent >= 0)
);
create unique index if not exists uk_appointment_active_patient_slot on appointment_order(patient_id, slot_id) where status in ('LOCKED', 'PAID');
create index if not exists idx_appointment_patient_created on appointment_order(patient_id, created_at desc);
create index if not exists idx_appointment_expire on appointment_order(expire_at) where status = 'LOCKED';
comment on table appointment_order is 'C端挂号订单表';

-- 挂号候补队列表
create table if not exists appointment_waitlist (
                                                    id bigint generated by default as identity primary key, -- 候补记录主键
                                                    patient_id bigint not null references patient_profile(id), -- 候补患者
                                                    slot_id bigint not null references schedule_slot(id), -- 候补号源时段
                                                    queue_no integer not null, -- 候补排队序号
                                                    status varchar(20) not null default 'WAITING', -- 候补状态
                                                    notified_at timestamptz, -- 通知候补时间
                                                    created_at timestamptz not null default now(), -- 创建时间
                                                    updated_at timestamptz not null default now(), -- 更新时间
                                                    constraint uk_waitlist_patient_slot unique (patient_id, slot_id),
                                                    constraint uk_waitlist_slot_queue unique (slot_id, queue_no),
                                                    constraint ck_waitlist_status check (status in ('WAITING', 'NOTIFIED', 'CANCELLED', 'EXPIRED'))
);
comment on table appointment_waitlist is '挂号候补队列表';

-- 支付抽象订单表
create table if not exists payment_order (
                                             id bigint generated by default as identity primary key, -- 支付单主键
                                             appointment_order_id bigint references appointment_order(id), -- 关联挂号订单
                                             drug_order_id bigint, -- 关联购药订单，后续通过外键约束关联
                                             payer_user_id bigint not null references c_user(id), -- 付款C端用户
                                             amount_cent integer not null, -- 应付金额，单位分
                                             status varchar(20) not null default 'PENDING', -- 支付状态
                                             expire_at timestamptz not null, -- 支付到期时间
                                             paid_at timestamptz, -- 支付完成时间
                                             provider_transaction_id varchar(128), -- 外部支付流水号
                                             created_at timestamptz not null default now(), -- 创建时间
                                             updated_at timestamptz not null default now(), -- 更新时间
                                             constraint uk_payment_provider_transaction unique (provider_transaction_id),
                                             constraint ck_payment_business check (num_nonnulls(appointment_order_id, drug_order_id) = 1),
                                             constraint ck_payment_status check (status in ('PENDING', 'SUCCESS', 'FAILED', 'CLOSED')),
                                             constraint ck_payment_amount check (amount_cent >= 0)
);
create index if not exists idx_payment_payer_created on payment_order(payer_user_id, created_at desc);
create index if not exists idx_payment_expire on payment_order(expire_at) where status = 'PENDING';
create unique index if not exists uk_payment_appointment_order on payment_order(appointment_order_id) where appointment_order_id is not null;
create unique index if not exists uk_payment_drug_order on payment_order(drug_order_id) where drug_order_id is not null;
comment on table payment_order is '抽象支付订单表，且仅关联一个挂号订单或购药订单';

-- 在线问诊表
create table if not exists consultation (
                                            id bigint generated by default as identity primary key, -- 问诊主键
                                            appointment_id bigint not null references appointment_order(id), -- 关联挂号订单
                                            patient_id bigint not null references patient_profile(id), -- 问诊患者
                                            doctor_id bigint not null references doctor(id), -- 接诊医生
                                            status varchar(20) not null default 'DRAFT', -- 问诊状态
                                            pre_consultation jsonb not null default '{}'::jsonb, -- 预问诊结构化内容
                                            pre_consultation_submitted_at timestamptz, -- 预问诊提交给医生的时间
                                            started_at timestamptz, -- 问诊开始时间
                                            completed_at timestamptz, -- 问诊结束时间
                                            created_at timestamptz not null default now(), -- 创建时间
                                            updated_at timestamptz not null default now(), -- 更新时间
                                            constraint uk_consultation_appointment unique (appointment_id),
                                            constraint ck_consultation_status check (status in ('DRAFT', 'PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
);
create index if not exists idx_consultation_patient_created on consultation(patient_id, created_at desc);
create index if not exists idx_consultation_doctor_status on consultation(doctor_id, status, created_at desc);
comment on table consultation is '在线文字问诊表';

-- 问诊文字消息表
create table if not exists consultation_message (
                                                    id bigint generated by default as identity primary key, -- 消息主键
                                                    consultation_id bigint not null references consultation(id), -- 所属问诊
                                                    sender_type varchar(20) not null, -- 发送方类型
                                                    sender_id bigint, -- 发送方业务主键
                                                    content varchar(2000) not null, -- 文本消息内容
                                                    created_at timestamptz not null default now(), -- 创建时间
                                                    constraint ck_consultation_message_sender check (sender_type in ('PATIENT', 'DOCTOR', 'SYSTEM'))
);
create index if not exists idx_consultation_message_time on consultation_message(consultation_id, created_at);
comment on table consultation_message is '问诊文字消息表';

-- 药品目录主表
create table if not exists drug (
                                    id bigint generated by default as identity primary key, -- 药品主键
                                    name varchar(128) not null, -- 药品名称
                                    specification varchar(256) not null, -- 药品规格
                                    manufacturer varchar(256), -- 生产厂家
                                    approval_number varchar(128), -- 批准文号
                                    unit varchar(32) not null default '盒', -- 最小销售单位
                                    status varchar(20) not null default 'ENABLED', -- 药品状态
                                    created_at timestamptz not null default now(), -- 创建时间
                                    updated_at timestamptz not null default now(), -- 更新时间
                                    deleted_at timestamptz, -- 软删除时间
                                    constraint uk_drug_approval_number unique (approval_number),
                                    constraint ck_drug_status check (status in ('ENABLED', 'DISABLED'))
);
create index if not exists idx_drug_name on drug(name) where deleted_at is null;
comment on table drug is '药品目录主表';

-- 医生签发处方表
create table if not exists prescription (
                                            id bigint generated by default as identity primary key, -- 处方主键
                                            consultation_id bigint not null references consultation(id), -- 关联问诊
                                            patient_id bigint not null references patient_profile(id), -- 患者
                                            doctor_id bigint not null references doctor(id), -- 开方医生
                                            status varchar(20) not null default 'ISSUED', -- 处方状态
                                            diagnosis_summary varchar(2000), -- 医生填写的诊疗摘要
                                            interpretation text, -- 医生确认后的处方解读
                                            issued_at timestamptz not null default now(), -- 签发时间
                                            created_at timestamptz not null default now(), -- 创建时间
                                            updated_at timestamptz not null default now(), -- 更新时间
                                            constraint ck_prescription_status check (status in ('DRAFT', 'ISSUED', 'CANCELLED', 'COMPLETED'))
);
create index if not exists idx_prescription_patient_issued on prescription(patient_id, issued_at desc);
create index if not exists idx_prescription_consultation on prescription(consultation_id);
comment on table prescription is '医生签发电子处方表';

-- 处方药品明细表
create table if not exists prescription_item (
                                                 id bigint generated by default as identity primary key, -- 处方明细主键
                                                 prescription_id bigint not null references prescription(id), -- 所属处方
                                                 drug_id bigint not null references drug(id), -- 药品主数据
                                                 drug_name_snapshot varchar(128) not null, -- 开方时药品名称快照
                                                 specification_snapshot varchar(256) not null, -- 开方时规格快照
                                                 dosage varchar(128) not null, -- 单次用量
                                                 frequency varchar(128) not null, -- 用药频次
                                                 usage_method varchar(128) not null, -- 用药方式
                                                 duration_days integer not null, -- 用药天数
                                                 quantity integer not null, -- 开方数量
                                                 created_at timestamptz not null default now(), -- 创建时间
                                                 constraint ck_prescription_item_duration check (duration_days > 0),
                                                 constraint ck_prescription_item_quantity check (quantity > 0)
);
create index if not exists idx_prescription_item_prescription on prescription_item(prescription_id);
comment on table prescription_item is '处方药品明细表';

-- 药店表
create table if not exists pharmacy (
                                        id bigint generated by default as identity primary key, -- 药店主键
                                        name varchar(128) not null, -- 药店名称
                                        address varchar(500) not null, -- 药店地址
                                        longitude numeric(10, 7), -- 经度
                                        latitude numeric(10, 7), -- 纬度
                                        delivery_eta_minutes integer not null default 60, -- 快递预计送达分钟数
                                        phone varchar(20), -- 药店联系电话，仅限演示环境
                                        status varchar(20) not null default 'ENABLED', -- 药店状态
                                        created_at timestamptz not null default now(), -- 创建时间
                                        updated_at timestamptz not null default now(), -- 更新时间
                                        deleted_at timestamptz, -- 软删除时间
                                        constraint ck_pharmacy_status check (status in ('ENABLED', 'DISABLED')),
                                        constraint ck_pharmacy_delivery_eta check (delivery_eta_minutes > 0)
);
create index if not exists idx_pharmacy_status on pharmacy(status) where deleted_at is null;
comment on table pharmacy is '药店基础信息表';

-- 药店药品库存表
create table if not exists pharmacy_drug_stock (
                                                   id bigint generated by default as identity primary key, -- 库存主键
                                                   pharmacy_id bigint not null references pharmacy(id), -- 所属药店
                                                   drug_id bigint not null references drug(id), -- 药品主数据
                                                   available_count integer not null default 0, -- 可售库存数量
                                                   locked_count integer not null default 0, -- 待支付锁定库存数量
                                                   safety_stock integer not null default 0, -- 安全库存阈值
                                                   unit_price_cent integer not null, -- 单价，单位分
                                                   updated_at timestamptz not null default now(), -- 更新时间
                                                   constraint uk_pharmacy_drug_stock unique (pharmacy_id, drug_id),
                                                   constraint ck_stock_count check (available_count >= 0 and locked_count >= 0 and safety_stock >= 0),
                                                   constraint ck_stock_price check (unit_price_cent >= 0)
);
create index if not exists idx_pharmacy_drug_stock_drug on pharmacy_drug_stock(drug_id, available_count);
comment on table pharmacy_drug_stock is '药店药品实时库存表';

-- 购药订单表
create table if not exists drug_order (
                                          id bigint generated by default as identity primary key, -- 购药订单主键
                                          patient_id bigint not null references patient_profile(id), -- 购药患者
                                          prescription_id bigint not null references prescription(id), -- 使用处方
                                          pharmacy_id bigint not null references pharmacy(id), -- 供药药店
                                          status varchar(20) not null default 'PENDING_PAYMENT', -- 购药订单状态
                                          delivery_method varchar(20) not null default 'COURIER', -- 固定快递配送方式
                                          delivery_address varchar(500) not null, -- 快递配送收货地址
                                          logistics_status varchar(20), -- 快递物流状态，支付后开始流转
                                          logistics_company varchar(64), -- 快递公司名称
                                          tracking_no varchar(64), -- 快递单号
                                          shipped_at timestamptz, -- 药店发货时间
                                          delivered_at timestamptz, -- 快递签收待确认时间
                                          received_at timestamptz, -- 用户确认收货时间
                                          amount_cent integer not null, -- 订单金额，单位分
                                          expire_at timestamptz, -- 待支付到期时间
                                          paid_at timestamptz, -- 支付时间
                                          cancelled_at timestamptz, -- 取消时间
                                          created_at timestamptz not null default now(), -- 创建时间
                                          updated_at timestamptz not null default now(), -- 更新时间
                                          constraint ck_drug_order_status check (status in ('DRAFT', 'PENDING_PAYMENT', 'PAID', 'CANCELLED', 'EXPIRED')),
                                          constraint ck_drug_order_delivery check (delivery_method = 'COURIER'),
                                          constraint ck_drug_order_logistics_status check (logistics_status is null or logistics_status in ('PENDING_SHIPMENT', 'IN_TRANSIT', 'TO_RECEIVE', 'RECEIVED')),
                                          constraint ck_drug_order_amount check (amount_cent >= 0)
);
create index if not exists idx_drug_order_patient_created on drug_order(patient_id, created_at desc);
create index if not exists idx_drug_order_expire on drug_order(expire_at) where status = 'PENDING_PAYMENT';
create index if not exists idx_drug_order_logistics on drug_order(patient_id, logistics_status, updated_at desc) where logistics_status is not null;
comment on table drug_order is 'C端处方购药订单表';

-- 补充购药订单支付外键，避免 payment_order 的多态关联产生孤儿数据
alter table payment_order
    add constraint fk_payment_drug_order
        foreign key (drug_order_id) references drug_order(id);

-- 购药订单物流轨迹表
create table if not exists drug_order_logistics_trace (
                                                          id bigint generated by default as identity primary key, -- 物流轨迹主键
                                                          drug_order_id bigint not null references drug_order(id), -- 所属购药订单
                                                          logistics_status varchar(20) not null, -- 当前物流状态快照
                                                          node varchar(500) not null, -- 物流节点说明
                                                          occurred_at timestamptz not null, -- 节点发生时间
                                                          created_at timestamptz not null default now(), -- 创建时间
                                                          constraint ck_logistics_trace_status check (logistics_status in ('PENDING_SHIPMENT', 'IN_TRANSIT', 'TO_RECEIVE', 'RECEIVED'))
);
create index if not exists idx_logistics_trace_order_time on drug_order_logistics_trace(drug_order_id, occurred_at desc);
comment on table drug_order_logistics_trace is '购药订单快递物流轨迹表';

-- 购药订单药品明细表
create table if not exists drug_order_item (
                                               id bigint generated by default as identity primary key, -- 购药明细主键
                                               drug_order_id bigint not null references drug_order(id), -- 所属购药订单
                                               prescription_item_id bigint not null references prescription_item(id), -- 对应处方药品明细
                                               drug_id bigint not null references drug(id), -- 药品主数据
                                               drug_name_snapshot varchar(128) not null, -- 下单时药品名称快照
                                               specification_snapshot varchar(256) not null, -- 下单时规格快照
                                               quantity integer not null, -- 购买数量
                                               unit_price_cent integer not null, -- 下单单价，单位分
                                               created_at timestamptz not null default now(), -- 创建时间
                                               constraint ck_drug_order_item_quantity check (quantity > 0),
                                               constraint ck_drug_order_item_price check (unit_price_cent >= 0)
);
create index if not exists idx_drug_order_item_order on drug_order_item(drug_order_id);
comment on table drug_order_item is '购药订单药品明细表';

-- 患者检查报告表
create table if not exists patient_report (
                                              id bigint generated by default as identity primary key, -- 报告主键
                                              patient_id bigint not null references patient_profile(id), -- 所属患者
                                              report_name varchar(256) not null, -- 报告名称
                                              report_date date not null, -- 报告日期
                                              source varchar(64), -- 报告来源
                                              interpretation text, -- 报告解读内容
                                              interpretation_status varchar(20) not null default 'PENDING', -- 解读生成状态
                                              created_at timestamptz not null default now(), -- 创建时间
                                              updated_at timestamptz not null default now(), -- 更新时间
                                              deleted_at timestamptz, -- 软删除时间
                                              constraint ck_report_interpretation_status check (interpretation_status in ('PENDING', 'READY', 'FAILED'))
);
create index if not exists idx_patient_report_patient_date on patient_report(patient_id, report_date desc) where deleted_at is null;
comment on table patient_report is '患者检查报告表';

-- 检查报告指标明细表
create table if not exists patient_report_indicator (
                                                        id bigint generated by default as identity primary key, -- 报告指标主键
                                                        report_id bigint not null references patient_report(id), -- 所属检查报告
                                                        name varchar(128) not null, -- 指标名称
                                                        value varchar(128) not null, -- 指标检测值
                                                        unit varchar(64), -- 指标单位
                                                        reference_range varchar(256), -- 指标参考区间
                                                        created_at timestamptz not null default now() -- 创建时间
);
create index if not exists idx_report_indicator_report on patient_report_indicator(report_id);
comment on table patient_report_indicator is '检查报告指标明细表';

-- 用药提醒计划表
create table if not exists medication_plan (
                                               id bigint generated by default as identity primary key, -- 用药计划主键
                                               patient_id bigint not null references patient_profile(id), -- 所属患者
                                               prescription_item_id bigint not null references prescription_item(id), -- 对应处方明细
                                               drug_name_snapshot varchar(128) not null, -- 药品名称快照
                                               dosage varchar(128) not null, -- 单次用量
                                               frequency varchar(128) not null, -- 用药频次
                                               reminder_times jsonb not null default '[]'::jsonb, -- 每日提醒时间数组
                                               next_reminder_at timestamptz, -- 下次提醒时间
                                               status varchar(20) not null default 'ACTIVE', -- 提醒状态
                                               created_at timestamptz not null default now(), -- 创建时间
                                               updated_at timestamptz not null default now(), -- 更新时间
                                               constraint ck_medication_plan_status check (status in ('ACTIVE', 'PAUSED', 'COMPLETED'))
);
create index if not exists idx_medication_plan_patient_status on medication_plan(patient_id, status, next_reminder_at);
comment on table medication_plan is '患者用药提醒计划表';

-- 随访计划表
create table if not exists follow_up_plan (
                                              id bigint generated by default as identity primary key, -- 随访计划主键
                                              patient_id bigint not null references patient_profile(id), -- 所属患者
                                              appointment_id bigint references appointment_order(id), -- 关联挂号订单
                                              consultation_id bigint references consultation(id), -- 关联问诊记录
                                              type varchar(64) not null, -- 随访类型
                                              content varchar(2000) not null, -- 随访内容
                                              due_at timestamptz not null, -- 建议完成时间
                                              remind_at timestamptz, -- 用户确认的提醒时间
                                              status varchar(20) not null default 'PENDING_CONFIRM', -- 随访状态
                                              created_at timestamptz not null default now(), -- 创建时间
                                              updated_at timestamptz not null default now(), -- 更新时间
                                              constraint ck_follow_up_status check (status in ('PENDING_CONFIRM', 'CONFIRMED', 'COMPLETED', 'CANCELLED'))
);
create index if not exists idx_follow_up_patient_status on follow_up_plan(patient_id, status, due_at);
comment on table follow_up_plan is '患者随访计划表';

-- C端站内通知表
create table if not exists notification (
                                            id bigint generated by default as identity primary key, -- 通知主键
                                            user_id bigint not null references c_user(id), -- 接收C端用户
                                            patient_id bigint references patient_profile(id), -- 通知所属就诊人，可为空
                                            patient_name_snapshot varchar(64), -- 通知生成时的就诊人姓名快照
                                            type varchar(64) not null, -- 通知业务类型
                                            title varchar(256) not null, -- 通知标题
                                            content text not null, -- 通知正文
                                            payload jsonb not null default '{}'::jsonb, -- 跳转和业务扩展参数
                                            read_at timestamptz, -- 已读时间
                                            created_at timestamptz not null default now(), -- 创建时间
                                            deleted_at timestamptz -- 软删除时间
);
create index if not exists idx_notification_user_created on notification(user_id, created_at desc) where deleted_at is null;
create index if not exists idx_notification_user_patient_created on notification(user_id, patient_id, created_at desc) where deleted_at is null;
create index if not exists idx_notification_user_unread on notification(user_id, created_at desc) where read_at is null and deleted_at is null;
comment on table notification is 'C端站内通知表';

-- Agent工具执行审计表
create table if not exists agent_tool_audit (
                                                id bigint generated by default as identity primary key, -- 审计主键
                                                session_id varchar(128) not null, -- Agent会话标识
                                                tool_call_id varchar(128) not null, -- Agent工具调用标识
                                                tool_name varchar(128) not null, -- 已执行的白名单工具名称
                                                user_id bigint not null references c_user(id), -- 发起操作的C端用户
                                                patient_id bigint references patient_profile(id), -- 当前就诊人，可为空
                                                patient_name_snapshot varchar(64), -- 执行时的就诊人名称脱敏摘要
                                                argument_summary jsonb not null default '{}'::jsonb, -- 脱敏后的请求参数摘要
                                                success boolean not null, -- 工具执行是否成功
                                                result_code varchar(5) not null, -- 五位业务码
                                                result_summary jsonb not null default '{}'::jsonb, -- 脱敏后的结果摘要
                                                trace_id varchar(64) not null, -- 请求链路追踪标识
                                                duration_ms integer not null check (duration_ms >= 0), -- 工具执行耗时，单位毫秒
                                                created_at timestamptz not null default now(), -- 创建时间
                                                constraint uk_agent_tool_audit_session_call unique (session_id, tool_call_id)
);
create index if not exists idx_agent_tool_audit_user_created on agent_tool_audit(user_id, created_at desc);
create index if not exists idx_agent_tool_audit_trace on agent_tool_audit(trace_id);
comment on table agent_tool_audit is 'Agent-BFF工具执行审计表，仅保存脱敏摘要';


/*-- 将原账号一对一关联改为账号拥有多个就诊人
alter table patient_profile rename column user_id to owner_user_id;
alter table patient_profile drop constraint uk_patient_profile_user;
alter table patient_profile add column relation varchar(16) not null default 'SELF';
alter table patient_profile add column active boolean not null default true;
alter table patient_profile add constraint ck_patient_profile_relation check (relation in ('SELF', 'SPOUSE', 'PARENT', 'CHILD', 'OTHER'));
create index idx_patient_profile_owner_active on patient_profile(owner_user_id, active, created_at desc) where deleted_at is null;
create unique index uk_patient_profile_owner_self on patient_profile(owner_user_id) where relation = 'SELF' and active = true and deleted_at is null;
create unique index uk_patient_profile_owner_id_card on patient_profile(owner_user_id, id_card_no) where id_card_no is not null and active = true and deleted_at is null;

-- 通知增加就诊人维度，历史通知允许为空
alter table notification add column patient_id bigint references patient_profile(id);
alter table notification add column patient_name_snapshot varchar(64);
create index idx_notification_user_patient_created on notification(user_id, patient_id, created_at desc) where deleted_at is null;

-- Agent 工具审计补充就诊人名称摘要
alter table agent_tool_audit add column patient_name_snapshot varchar(64);*/
commit;
