-- 医院表
CREATE TABLE hospital (
                          id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name            varchar(100) NOT NULL,
                          level           varchar(20),
                          description     varchar(500),
                          address         varchar(200),
                          contact         varchar(100),
                          status          varchar(20) NOT NULL DEFAULT 'ENABLED',
                          created_at      timestamptz NOT NULL DEFAULT now(),
                          updated_at      timestamptz NOT NULL DEFAULT now(),
                          deleted_at      timestamptz,
                          CONSTRAINT ck_hospital_status CHECK (status IN ('ENABLED', 'DISABLED'))
);

-- 科室表
CREATE TABLE department (
                            id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            hospital_id     bigint NOT NULL,
                            name            varchar(64) NOT NULL,
                            head_doctor_id  bigint,
                            description     varchar(500),
                            status          varchar(20) NOT NULL DEFAULT 'ENABLED',
                            created_at      timestamptz NOT NULL DEFAULT now(),
                            updated_at      timestamptz NOT NULL DEFAULT now(),
                            deleted_at      timestamptz,
                            CONSTRAINT fk_department_hospital FOREIGN KEY (hospital_id) REFERENCES hospital(id),
                            CONSTRAINT ck_department_status CHECK (status IN ('ENABLED', 'DISABLED'))
);

-- 医生表
CREATE TABLE doctor (
                        id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        hospital_id          bigint NOT NULL,
                        dept_id              bigint NOT NULL,
                        name                 varchar(64) NOT NULL,
                        title                varchar(64),
                        specialty            varchar(1000),
                        introduction         varchar(4000),
                        license_no           varchar(64),
                        phone                varchar(32),
                        registration_fee_cent integer NOT NULL DEFAULT 0,
                        status               varchar(20) NOT NULL DEFAULT 'ENABLED',
                        created_at           timestamptz NOT NULL DEFAULT now(),
                        updated_at           timestamptz NOT NULL DEFAULT now(),
                        deleted_at           timestamptz,
                        CONSTRAINT fk_doctor_hospital FOREIGN KEY (hospital_id) REFERENCES hospital(id),
                        CONSTRAINT fk_doctor_dept FOREIGN KEY (dept_id) REFERENCES department(id),
                        CONSTRAINT ck_doctor_status CHECK (status IN ('ENABLED', 'DISABLED', 'SUSPENDED'))
);
CREATE INDEX idx_doctor_dept_status ON doctor(dept_id, status) WHERE deleted_at IS NULL;


-- 排班表
CREATE TABLE schedule (
                          id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          doctor_id       bigint NOT NULL,
                          schedule_date   date NOT NULL,
                          shift           varchar(10) NOT NULL,
                          total_slots     integer NOT NULL DEFAULT 0,
                          status          varchar(20) NOT NULL DEFAULT 'DRAFT',
                          published_at    timestamptz,
                          created_at      timestamptz NOT NULL DEFAULT now(),
                          updated_at      timestamptz NOT NULL DEFAULT now(),
                          deleted_at      timestamptz,
                          CONSTRAINT fk_schedule_doctor FOREIGN KEY (doctor_id) REFERENCES doctor(id),
                          CONSTRAINT uk_schedule_doctor_date_shift UNIQUE (doctor_id, schedule_date, shift),
                          CONSTRAINT ck_schedule_shift CHECK (shift IN ('MORNING', 'AFTERNOON')),
                          CONSTRAINT ck_schedule_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED'))
);

-- 号源时段表
CREATE TABLE slot (
                      id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      schedule_id     bigint NOT NULL,
                      start_time      time NOT NULL,
                      end_time        time NOT NULL,
                      total_count     integer NOT NULL,
                      remain_count    integer NOT NULL,
                      created_at      timestamptz NOT NULL DEFAULT now(),
                      updated_at      timestamptz NOT NULL DEFAULT now(),
                      deleted_at      timestamptz,
                      CONSTRAINT fk_slot_schedule FOREIGN KEY (schedule_id) REFERENCES schedule(id),
                      CONSTRAINT ck_slot_time CHECK (end_time > start_time),
                      CONSTRAINT ck_slot_count CHECK (total_count >= 0 AND remain_count BETWEEN 0 AND total_count)
);

-- C端用户表
CREATE TABLE c_user (
                        id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        account         varchar(32) NOT NULL UNIQUE,
                        password_hash   varchar(100) NOT NULL,
                        status          varchar(20) NOT NULL DEFAULT 'ENABLED',
                        created_at      timestamptz NOT NULL DEFAULT now(),
                        updated_at      timestamptz NOT NULL DEFAULT now(),
                        deleted_at      timestamptz,
                        CONSTRAINT ck_c_user_status CHECK (status IN ('ENABLED', 'DISABLED'))
);

-- B端用户表（医生/科室负责人/管理员账号，与 doctor 表解耦）
-- role: ADMIN 医院管理员（无需 doctor_id）；DEPT_HEAD 科室负责人（经 doctor_id 取科室）；DOCTOR 普通医生（经 doctor_id 关联医生）
CREATE TABLE b_user (
                        id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        account         varchar(32) NOT NULL UNIQUE,
                        password_hash   varchar(100) NOT NULL,
                        role            varchar(20) NOT NULL,          -- ADMIN / DEPT_HEAD / DOCTOR
                        hospital_id     bigint NOT NULL,               -- 所属医院（数据隔离）
                        doctor_id       bigint,                        -- role=DOCTOR/DEPT_HEAD 时关联医生表
                        status          varchar(20) NOT NULL DEFAULT 'ENABLED',
                        created_at      timestamptz NOT NULL DEFAULT now(),
                        updated_at      timestamptz NOT NULL DEFAULT now(),
                        deleted_at      timestamptz,
                        CONSTRAINT fk_b_user_hospital FOREIGN KEY (hospital_id) REFERENCES hospital(id),
                        CONSTRAINT fk_b_user_doctor FOREIGN KEY (doctor_id) REFERENCES doctor(id),
                        CONSTRAINT ck_b_user_role CHECK (role IN ('ADMIN', 'DEPT_HEAD', 'DOCTOR')),
                        CONSTRAINT ck_b_user_status CHECK (status IN ('ENABLED', 'DISABLED'))
);
CREATE INDEX idx_b_user_hospital_role ON b_user(hospital_id, role) WHERE deleted_at IS NULL;

/*业务规则：
- 新增医生记录（doctor）时必须同步创建 b_user 账号（role=DOCTOR），账号/密码由管理员在创建时设置（`POST /api/b/admin/doctors`）；管理员可随时修改医生登录账号、重置登录密码（`PUT /api/b/admin/doctors/{id}/account`、`PUT /api/b/admin/doctors/{id}/password`）。
- 停用医生（doctor.status=DISABLED）时，若存在关联 b_user，建议同步停用（或由管理员决定）。
- `ADMIN` 角色无 `doctor_id`，数据权限仅按 `hospital_id` 过滤。
- `DEPT_HEAD` 的科室归属通过 `b_user.doctor_id → doctor.dept_id` 获取。
- `DOCTOR` 角色的数据权限为本人（`hospital_id + doctor_id`）。*/

-- B端刷新令牌（对应 b_user，参考 c_refresh_token）
CREATE TABLE b_refresh_token (
                                 id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 user_id         bigint NOT NULL REFERENCES b_user(id),
                                 token_hash      varchar(128) NOT NULL,
                                 expired_at      timestamptz NOT NULL,
                                 revoked_at      timestamptz,
                                 created_at      timestamptz NOT NULL DEFAULT now(),
                                 CONSTRAINT uk_b_refresh_token_hash UNIQUE (token_hash)
);

-- 患者表（就诊人）
CREATE TABLE patient (
                         id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name                 varchar(64) NOT NULL,
                         id_card_ciphertext   varchar(512),
                         phone_ciphertext     varchar(512),
                         gender               varchar(10),
                         date_of_birth        date,
                         emergency_contact    varchar(256),
                         created_at           timestamptz NOT NULL DEFAULT now(),
                         updated_at           timestamptz NOT NULL DEFAULT now(),
                         deleted_at           timestamptz,
                         CONSTRAINT ck_patient_gender CHECK (gender IN ('MALE', 'FEMALE', 'UNKNOWN'))
);

-- 号源快照表（每个号源独立记录）
CREATE TABLE slot_snapshot (
                               id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               slot_id         bigint NOT NULL,
                               patient_id      bigint,
                               status          varchar(20) NOT NULL DEFAULT 'AVAILABLE',
                               locked_at       timestamptz,
                               sold_at         timestamptz,
                               created_at      timestamptz NOT NULL DEFAULT now(),
                               updated_at      timestamptz NOT NULL DEFAULT now(),
                               deleted_at      timestamptz,
                               CONSTRAINT fk_slot_snapshot_slot FOREIGN KEY (slot_id) REFERENCES slot(id),
                               CONSTRAINT fk_slot_snapshot_patient FOREIGN KEY (patient_id) REFERENCES patient(id),
                               CONSTRAINT ck_slot_snapshot_status CHECK (status IN ('AVAILABLE', 'LOCKED', 'SOLD', 'EXPIRED', 'RELEASED'))
);
CREATE INDEX idx_slot_snapshot_slot_status ON slot_snapshot(slot_id, status) WHERE deleted_at IS NULL;

-- 患者用户关联表（家庭成员关系）
CREATE TABLE patient_user_relation (
                                       id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       user_id         bigint NOT NULL,
                                       patient_id      bigint NOT NULL,
                                       relationship    varchar(20) NOT NULL,
                                       is_default      boolean NOT NULL DEFAULT false,
                                       created_at      timestamptz NOT NULL DEFAULT now(),
                                       updated_at      timestamptz NOT NULL DEFAULT now(),
                                       deleted_at      timestamptz,
                                       CONSTRAINT fk_patient_user_relation_user FOREIGN KEY (user_id) REFERENCES c_user(id),
                                       CONSTRAINT fk_patient_user_relation_patient FOREIGN KEY (patient_id) REFERENCES patient(id),
                                       CONSTRAINT ck_patient_user_relation_relationship CHECK (relationship IN ('SELF', 'SPOUSE', 'PARENT', 'CHILD', 'OTHER'))
);
CREATE INDEX idx_patient_user_relation_user ON patient_user_relation(user_id) WHERE deleted_at IS NULL;

-- 患者过敏史
CREATE TABLE patient_allergy (
                                 id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 patient_id      bigint NOT NULL,
                                 allergen        varchar(128) NOT NULL,
                                 reaction        varchar(512),
                                 severity        varchar(20),
                                 created_at      timestamptz NOT NULL DEFAULT now(),
                                 updated_at      timestamptz NOT NULL DEFAULT now(),
                                 deleted_at      timestamptz,
                                 CONSTRAINT fk_patient_allergy_patient FOREIGN KEY (patient_id) REFERENCES patient(id),
                                 CONSTRAINT ck_patient_allergy_severity CHECK (severity IN ('MILD', 'MODERATE', 'SEVERE'))
);

-- 患者既往史
CREATE TABLE patient_medical_history (
                                         id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         patient_id      bigint NOT NULL,
                                         content         varchar(2000) NOT NULL,
                                         occurred_at     date,
                                         created_at      timestamptz NOT NULL DEFAULT now(),
                                         updated_at      timestamptz NOT NULL DEFAULT now(),
                                         deleted_at      timestamptz,
                                         CONSTRAINT fk_patient_medical_history_patient FOREIGN KEY (patient_id) REFERENCES patient(id)
);


-- 挂号订单表
CREATE TABLE appointment (
                             id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             slot_snapshot_id     bigint NOT NULL,
                             patient_id           bigint NOT NULL,
                             doctor_id            bigint NOT NULL,
                             status               varchar(20) NOT NULL DEFAULT 'UNPAID',
                             amount_cent          integer NOT NULL,
                             expire_at            timestamptz,
                             paid_at              timestamptz,
                             cancelled_at         timestamptz,
                             created_at           timestamptz NOT NULL DEFAULT now(),
                             updated_at           timestamptz NOT NULL DEFAULT now(),
                             deleted_at           timestamptz,
                             CONSTRAINT fk_appointment_slot_snapshot FOREIGN KEY (slot_snapshot_id) REFERENCES slot_snapshot(id),
                             CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES patient(id),
                             CONSTRAINT fk_appointment_doctor FOREIGN KEY (doctor_id) REFERENCES doctor(id),
                             CONSTRAINT ck_appointment_status CHECK (status IN ('UNPAID', 'PAID', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'NO_SHOW')),
                             CONSTRAINT ck_appointment_amount CHECK (amount_cent >= 0)
);
CREATE INDEX idx_appointment_patient_created ON appointment(patient_id, created_at DESC) WHERE deleted_at IS NULL;

-- 问诊记录表
CREATE TABLE consult_record (
                                id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                appointment_id       bigint NOT NULL,
                                doctor_id            bigint NOT NULL,
                                patient_id           bigint NOT NULL,
                                status               varchar(20) NOT NULL DEFAULT 'PENDING',
                                ai_summary           jsonb,
                                doctor_note          text,
                                started_at           timestamptz,
                                ended_at             timestamptz,
                                created_at           timestamptz NOT NULL DEFAULT now(),
                                updated_at           timestamptz NOT NULL DEFAULT now(),
                                deleted_at           timestamptz,
                                CONSTRAINT fk_consult_record_appointment FOREIGN KEY (appointment_id) REFERENCES appointment(id),
                                CONSTRAINT fk_consult_record_doctor FOREIGN KEY (doctor_id) REFERENCES doctor(id),
                                CONSTRAINT fk_consult_record_patient FOREIGN KEY (patient_id) REFERENCES patient(id),
                                CONSTRAINT uk_consult_record_appointment UNIQUE (appointment_id),
                                CONSTRAINT ck_consult_record_status CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'NO_SHOW'))
);
CREATE INDEX idx_consult_record_doctor_status ON consult_record(doctor_id, status) WHERE deleted_at IS NULL;


-- 处方表
CREATE TABLE prescription (
                              id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              consult_id           bigint NOT NULL,
                              doctor_id            bigint NOT NULL,
                              patient_id           bigint NOT NULL,
                              status               varchar(20) NOT NULL DEFAULT 'DRAFT',
                              reject_reason        varchar(1000),
                              issued_at            timestamptz,
                              audited_at           timestamptz,
                              created_at           timestamptz NOT NULL DEFAULT now(),
                              updated_at           timestamptz NOT NULL DEFAULT now(),
                              deleted_at           timestamptz,
                              CONSTRAINT fk_prescription_consult FOREIGN KEY (consult_id) REFERENCES consult_record(id),
                              CONSTRAINT fk_prescription_doctor FOREIGN KEY (doctor_id) REFERENCES doctor(id),
                              CONSTRAINT fk_prescription_patient FOREIGN KEY (patient_id) REFERENCES patient(id),
                              CONSTRAINT ck_prescription_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

-- 药品目录
CREATE TABLE drug (
                      id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      hospital_id          bigint NOT NULL,
                      name                 varchar(200) NOT NULL,
                      specification        varchar(100) NOT NULL,
                      manufacturer         varchar(200),
                      approval_number      varchar(50),
                      unit                 varchar(32) NOT NULL DEFAULT '盒',
                      indication           text,
                      contraindication     text,
                      side_effect          text,
                      status               varchar(20) NOT NULL DEFAULT 'ENABLED',
                      created_at           timestamptz NOT NULL DEFAULT now(),
                      updated_at           timestamptz NOT NULL DEFAULT now(),
                      deleted_at           timestamptz,
                      CONSTRAINT fk_drug_hospital FOREIGN KEY (hospital_id) REFERENCES hospital(id),
                      CONSTRAINT uk_drug_hospital_approval UNIQUE (hospital_id, approval_number),
                       CONSTRAINT ck_drug_status CHECK (status IN ('ENABLED', 'DISABLED'))
);

-- 处方明细
CREATE TABLE prescription_item (
                                   id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   prescription_id bigint NOT NULL,
                                   drug_id         bigint NOT NULL,
                                   dosage          varchar(50) NOT NULL,
                                   frequency       varchar(50),
                                   usage_method    varchar(50) NOT NULL,
                                   days            smallint NOT NULL,
                                   quantity        smallint NOT NULL,
                                   created_at      timestamptz NOT NULL DEFAULT now(),
                                   CONSTRAINT fk_prescription_item_prescription FOREIGN KEY (prescription_id) REFERENCES prescription(id),
                                   CONSTRAINT fk_prescription_item_drug FOREIGN KEY (drug_id) REFERENCES drug(id)
);

-- 药房
CREATE TABLE pharmacy (
                          id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          hospital_id     bigint NOT NULL,
                          name            varchar(128) NOT NULL,
                          address         varchar(500),
                          phone           varchar(32),
                          is_default      boolean NOT NULL DEFAULT false,
                          status          varchar(20) NOT NULL DEFAULT 'ENABLED',
                          created_at      timestamptz NOT NULL DEFAULT now(),
                          updated_at      timestamptz NOT NULL DEFAULT now(),
                          deleted_at      timestamptz,
                          CONSTRAINT fk_pharmacy_hospital FOREIGN KEY (hospital_id) REFERENCES hospital(id),
                          CONSTRAINT uk_pharmacy_hospital_name UNIQUE (hospital_id, name),
                          CONSTRAINT ck_pharmacy_status CHECK (status IN ('ENABLED', 'DISABLED'))
);

-- 药房药品库存
CREATE TABLE pharmacy_drug_stock (
                                     id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     pharmacy_id         bigint NOT NULL,
                                     drug_id             bigint NOT NULL,
                                     available_count     integer NOT NULL DEFAULT 0,
                                     locked_count        integer NOT NULL DEFAULT 0,
                                     safety_stock        integer NOT NULL DEFAULT 0,
                                     unit_price_cent     integer NOT NULL,
                                     updated_at          timestamptz NOT NULL DEFAULT now(),
                                     CONSTRAINT fk_pharmacy_drug_stock_pharmacy FOREIGN KEY (pharmacy_id) REFERENCES pharmacy(id),
                                     CONSTRAINT fk_pharmacy_drug_stock_drug FOREIGN KEY (drug_id) REFERENCES drug(id),
                                     CONSTRAINT uk_pharmacy_drug_stock UNIQUE (pharmacy_id, drug_id),
                                     CONSTRAINT ck_stock_count CHECK (available_count >= 0 AND locked_count >= 0 AND safety_stock >= 0)
);

-- 处方模板表
CREATE TABLE prescription_template (
                                       id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       hospital_id     bigint NOT NULL,               -- 所属医院
                                       dept_id         bigint,                        -- 关联科室，NULL 表示全院通用
                                       name            varchar(128) NOT NULL,         -- 模板名称
                                       doctor_id       bigint NOT NULL,               -- 创建人
                                       items           jsonb NOT NULL,                -- 药品明细 JSON，结构与处方明细一致
                                       status          varchar(20) NOT NULL DEFAULT 'ENABLED',
                                       created_at      timestamptz NOT NULL DEFAULT now(),
                                       updated_at      timestamptz NOT NULL DEFAULT now(),
                                       deleted_at      timestamptz,
                                       CONSTRAINT fk_template_hospital FOREIGN KEY (hospital_id) REFERENCES hospital(id),
                                       CONSTRAINT fk_template_dept FOREIGN KEY (dept_id) REFERENCES department(id),
                                       CONSTRAINT fk_template_doctor FOREIGN KEY (doctor_id) REFERENCES doctor(id),
                                       CONSTRAINT ck_template_status CHECK (status IN ('ENABLED', 'DISABLED'))
);

-- C端刷新令牌
CREATE TABLE c_refresh_token (
                                 id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 user_id         bigint NOT NULL REFERENCES c_user(id),
                                 token_hash      varchar(128) NOT NULL,
                                 expired_at      timestamptz NOT NULL,
                                 revoked_at      timestamptz,
                                 created_at      timestamptz NOT NULL DEFAULT now(),
                                 CONSTRAINT uk_c_refresh_token_hash UNIQUE (token_hash)
);

-- 导诊评估
CREATE TABLE triage_assessment (
                                   id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   patient_id      bigint NOT NULL REFERENCES patient(id),
                                   hospital_id     bigint NOT NULL REFERENCES hospital(id),
                                   symptom_input   jsonb NOT NULL,
                                   urgency         varchar(20) NOT NULL,
                                   recommended_departments jsonb NOT NULL DEFAULT '[]'::jsonb,
                                   created_at      timestamptz NOT NULL DEFAULT now(),
                                   updated_at      timestamptz NOT NULL DEFAULT now(),
                                   deleted_at      timestamptz,
                                   CONSTRAINT ck_triage_assessment_urgency CHECK (urgency IN ('LOW', 'MEDIUM', 'HIGH'))
);

-- 挂号候补
CREATE TABLE appointment_waitlist (
                                      id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      patient_id      bigint NOT NULL REFERENCES patient(id),
                                      slot_id         bigint NOT NULL REFERENCES slot(id),
                                      queue_no        integer NOT NULL,
                                      status          varchar(20) NOT NULL DEFAULT 'WAITING',
                                      created_at      timestamptz NOT NULL DEFAULT now(),
                                      updated_at      timestamptz NOT NULL DEFAULT now(),
                                      deleted_at      timestamptz,
                                      CONSTRAINT uk_waitlist_patient_slot UNIQUE (patient_id, slot_id),
                                      CONSTRAINT ck_waitlist_status CHECK (status IN ('WAITING', 'NOTIFIED', 'CANCELLED', 'EXPIRED'))
);

-- 问诊消息
CREATE TABLE consultation_message (
                                      id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      consult_id      bigint NOT NULL REFERENCES consult_record(id),
                                      sender_type     varchar(20) NOT NULL,
                                      content         varchar(2000) NOT NULL,
                                      created_at      timestamptz NOT NULL DEFAULT now(),
                                      deleted_at      timestamptz,
                                      CONSTRAINT ck_consultation_message_sender CHECK (sender_type IN ('PATIENT', 'DOCTOR', 'SYSTEM'))
);

-- 购药订单
CREATE TABLE drug_order (
                            id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            patient_id      bigint NOT NULL REFERENCES patient(id),
                            prescription_id bigint NOT NULL REFERENCES prescription(id),
                            pharmacy_id     bigint NOT NULL REFERENCES pharmacy(id),
                            delivery_method varchar(20) NOT NULL DEFAULT 'COURIER',
                            delivery_address varchar(500) NOT NULL,
                            status          varchar(20) NOT NULL DEFAULT 'PENDING_PAYMENT',
                            logistics_status varchar(30) NOT NULL DEFAULT 'PENDING_SHIPMENT',
                            amount_cent     integer NOT NULL,
                            expire_at       timestamptz NOT NULL,
                            logistics_company varchar(128),
                            tracking_no     varchar(64),
                            shipped_at      timestamptz,
                            delivered_at    timestamptz,
                            received_at     timestamptz,
                            created_at      timestamptz NOT NULL DEFAULT now(),
                            updated_at      timestamptz NOT NULL DEFAULT now(),
                            deleted_at      timestamptz,
                            CONSTRAINT ck_drug_order_status CHECK (status IN ('DRAFT', 'PENDING_PAYMENT', 'PAID', 'CANCELLED', 'EXPIRED')),
                             CONSTRAINT ck_drug_order_logistics_status CHECK (logistics_status IN ('PENDING_SHIPMENT', 'SHIPPED', 'IN_TRANSIT', 'TO_RECEIVE', 'RECEIVED'))
);

-- 支付订单
CREATE TABLE payment_order (
                               id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               appointment_id  bigint REFERENCES appointment(id),
                               drug_order_id   bigint REFERENCES drug_order(id),
                               payer_user_id   bigint NOT NULL REFERENCES c_user(id),
                               amount_cent     integer NOT NULL,
                               status          varchar(20) NOT NULL DEFAULT 'PENDING',
                               expire_at       timestamptz NOT NULL,
                               paid_at         timestamptz,
                               created_at      timestamptz NOT NULL DEFAULT now(),
                               updated_at      timestamptz NOT NULL DEFAULT now(),
                               CONSTRAINT ck_payment_business CHECK (num_nonnulls(appointment_id, drug_order_id) = 1),
                               CONSTRAINT ck_payment_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'CLOSED'))
);

-- 检查报告
CREATE TABLE patient_report (
                                id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                patient_id      bigint NOT NULL REFERENCES patient(id),
                                report_name     varchar(256) NOT NULL,
                                report_date     date NOT NULL,
                                interpretation_status varchar(20) NOT NULL DEFAULT 'PENDING',
                                interpretation  jsonb,
                                created_at      timestamptz NOT NULL DEFAULT now(),
                                updated_at      timestamptz NOT NULL DEFAULT now(),
                                deleted_at      timestamptz,
                                CONSTRAINT ck_report_interpretation_status CHECK (interpretation_status IN ('PENDING', 'READY', 'FAILED'))
);

-- 用药计划
CREATE TABLE medication_plan (
                                 id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 drug_order_id   bigint REFERENCES drug_order(id),
                                 patient_id      bigint NOT NULL REFERENCES patient(id),
                                 prescription_item_id bigint NOT NULL REFERENCES prescription_item(id),
                                 drug_name_snapshot varchar(128) NOT NULL,
                                 frequency       varchar(128) NOT NULL,
                                 usage_method    varchar(128),
                                 next_remind_at  timestamptz,
                                 status          varchar(20) NOT NULL DEFAULT 'ACTIVE',
                                 created_at      timestamptz NOT NULL DEFAULT now(),
                                 updated_at      timestamptz NOT NULL DEFAULT now(),
                                 deleted_at      timestamptz,
                                 CONSTRAINT ck_medication_plan_status CHECK (status IN ('ACTIVE', 'PAUSED', 'COMPLETED'))
);

-- 购药订单收货后自动开启用药提醒授权
CREATE TABLE drug_order_medication_reminder_activation (
                                 id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 drug_order_id   bigint NOT NULL UNIQUE REFERENCES drug_order(id),
                                 user_id         bigint NOT NULL REFERENCES c_user(id),
                                 patient_id      bigint NOT NULL REFERENCES patient(id),
                                 status          varchar(32) NOT NULL DEFAULT 'PENDING_RECEIPT',
                                 authorized_at   timestamptz NOT NULL DEFAULT now(),
                                 activated_at    timestamptz,
                                 created_at      timestamptz NOT NULL DEFAULT now(),
                                 updated_at      timestamptz NOT NULL DEFAULT now(),
                                 deleted_at      timestamptz,
                                 CONSTRAINT ck_drug_order_reminder_activation_status
                                     CHECK (status IN ('PENDING_RECEIPT', 'ACTIVATED'))
);

-- 随访计划
CREATE TABLE follow_up_plan (
                                id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                patient_id      bigint NOT NULL REFERENCES patient(id),
                                appointment_id  bigint REFERENCES appointment(id),
                                consult_id      bigint REFERENCES consult_record(id),
                                due_at          timestamptz NOT NULL,
                                remind_at       timestamptz,
                                status          varchar(20) NOT NULL DEFAULT 'PENDING_CONFIRM',
                                created_at      timestamptz NOT NULL DEFAULT now(),
                                updated_at      timestamptz NOT NULL DEFAULT now(),
                                deleted_at      timestamptz,
                                CONSTRAINT ck_follow_up_status CHECK (status IN ('PENDING_CONFIRM', 'CONFIRMED', 'COMPLETED', 'CANCELLED'))
);

-- 通知
CREATE TABLE notification (
                              id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              user_id         bigint NOT NULL REFERENCES c_user(id),
                              patient_id      bigint REFERENCES patient(id),
                              patient_name_snapshot varchar(64),
                              type            varchar(64) NOT NULL,
                              title           varchar(256) NOT NULL,
                              content         text NOT NULL,
                              payload         jsonb NOT NULL DEFAULT '{}'::jsonb,
                              read_at         timestamptz,
                              created_at      timestamptz NOT NULL DEFAULT now(),
                              deleted_at      timestamptz
);
