-- C端医生病历报告解读补充：在初始化脚本成功执行后运行，可重复执行。

-- 医生病历解读结果：以问诊记录为报告主体，后续解读生产链路仅写入 READY 结果供 C 端读取。
CREATE TABLE IF NOT EXISTS consultation_report_interpretation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consult_id bigint NOT NULL REFERENCES consult_record(id),
    content text,
    disclaimer varchar(500) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    generated_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT ck_consultation_report_interpretation_status
        CHECK (status IN ('PENDING', 'READY', 'FAILED'))
);

-- 同一份有效病历仅保留一条当前解读，软删除历史记录不影响后续重新生成。
CREATE UNIQUE INDEX IF NOT EXISTS uk_consultation_report_interpretation_active
    ON consultation_report_interpretation(consult_id)
    WHERE deleted_at IS NULL;

-- C端按病历读取 READY 解读时使用该索引过滤状态与软删除记录。
CREATE INDEX IF NOT EXISTS idx_consultation_report_interpretation_consult_status
    ON consultation_report_interpretation(consult_id, status)
    WHERE deleted_at IS NULL;
