-- ============================================================
-- C 端购药订单收货后自动开启用药提醒补充脚本
-- 执行环境：PostgreSQL
-- 用途：绑定支付后创建的用药计划与购药订单，并保存用户授权记录
-- 特性：可重复执行；历史用药计划不回填订单，不会被自动开启
-- ============================================================

-- 标识用药计划由哪一笔已支付购药订单创建，防止同一处方重复下单时串单启用。
ALTER TABLE medication_plan
    ADD COLUMN IF NOT EXISTS drug_order_id bigint REFERENCES drug_order(id);

-- 仅查询新订单关联的计划，供确认收货事务精确启用提醒。
CREATE INDEX IF NOT EXISTS idx_medication_plan_drug_order_id
    ON medication_plan(drug_order_id)
    WHERE deleted_at IS NULL;

-- 保存用户对某笔订单的自动提醒授权；一笔订单最多一条有效授权。
CREATE TABLE IF NOT EXISTS drug_order_medication_reminder_activation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_order_id bigint NOT NULL UNIQUE REFERENCES drug_order(id),
    user_id bigint NOT NULL REFERENCES c_user(id),
    patient_id bigint NOT NULL REFERENCES patient(id),
    status varchar(32) NOT NULL DEFAULT 'PENDING_RECEIPT',
    authorized_at timestamptz NOT NULL DEFAULT now(),
    activated_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT ck_drug_order_reminder_activation_status
        CHECK (status IN ('PENDING_RECEIPT', 'ACTIVATED'))
);
