-- C端创表补充：本脚本在初始创表.sql 成功执行后运行，可重复执行。

-- 预问诊内容与附件（兼容既有问诊记录）。
ALTER TABLE consult_record ADD COLUMN IF NOT EXISTS chief_complaint varchar(1000);
ALTER TABLE consult_record ADD COLUMN IF NOT EXISTS history_of_present_illness text;
ALTER TABLE consult_record ADD COLUMN IF NOT EXISTS attachments jsonb;

-- 支付渠道回调防重字段。
ALTER TABLE payment_order ADD COLUMN IF NOT EXISTS provider varchar(32);
ALTER TABLE payment_order ADD COLUMN IF NOT EXISTS provider_transaction_id varchar(128);

-- 购药订单展示快照，避免药房资料变更影响历史订单。
ALTER TABLE drug_order ADD COLUMN IF NOT EXISTS pharmacy_name_snapshot varchar(128);

-- 用药计划展示剂量与疗程。
ALTER TABLE medication_plan ADD COLUMN IF NOT EXISTS dosage varchar(128);
ALTER TABLE medication_plan ADD COLUMN IF NOT EXISTS duration_days smallint;
ALTER TABLE medication_plan ADD COLUMN IF NOT EXISTS end_at timestamptz;

-- 随访事项内容。
ALTER TABLE follow_up_plan ADD COLUMN IF NOT EXISTS follow_up_type varchar(64);
ALTER TABLE follow_up_plan ADD COLUMN IF NOT EXISTS content text;

-- 通知已读等状态更新的时间。
ALTER TABLE notification ADD COLUMN IF NOT EXISTS updated_at timestamptz;

-- 购药订单明细，固化下单时的药品名称、数量与价格。
CREATE TABLE IF NOT EXISTS drug_order_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_order_id bigint NOT NULL REFERENCES drug_order(id),
    drug_id bigint NOT NULL REFERENCES drug(id),
    drug_name_snapshot varchar(200) NOT NULL,
    quantity integer NOT NULL,
    unit_price_cent integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_drug_order_item_quantity CHECK (quantity > 0),
    CONSTRAINT ck_drug_order_item_price CHECK (unit_price_cent >= 0)
);

-- 购药订单物流轨迹，按发生时间展示。
CREATE TABLE IF NOT EXISTS drug_order_logistics_trace (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_order_id bigint NOT NULL REFERENCES drug_order(id),
    node varchar(500) NOT NULL,
    occurred_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- 检查报告指标明细。
CREATE TABLE IF NOT EXISTS patient_report_indicator (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id bigint NOT NULL REFERENCES patient_report(id),
    name varchar(128) NOT NULL,
    value varchar(128) NOT NULL,
    unit varchar(64),
    reference_range varchar(128),
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Agent经MCP调用C端Java API的审计记录，不保存模型推理或敏感原文。
CREATE TABLE IF NOT EXISTS agent_tool_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id varchar(128),
    user_id bigint NOT NULL REFERENCES c_user(id),
    tool_name varchar(128) NOT NULL,
    security_level varchar(8) NOT NULL,
    request_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    result_code varchar(64) NOT NULL,
    result_status varchar(16) NOT NULL,
    duration_ms integer,
    trace_id varchar(64),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_agent_tool_audit_level CHECK (security_level IN ('L1', 'L2', 'L3', 'L4')),
    CONSTRAINT ck_agent_tool_audit_status CHECK (result_status IN ('SUCCESS', 'FAILED', 'REJECTED'))
);

-- 为既有C端业务表补充数据完整性约束。
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_payment_amount') THEN
        ALTER TABLE payment_order ADD CONSTRAINT ck_payment_amount CHECK (amount_cent >= 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_drug_order_delivery') THEN
        ALTER TABLE drug_order ADD CONSTRAINT ck_drug_order_delivery CHECK (delivery_method = 'COURIER');
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_drug_order_logistics_status'
          AND conrelid = 'drug_order'::regclass
    ) THEN
    ALTER TABLE drug_order
        ADD CONSTRAINT ck_drug_order_logistics_status
            CHECK (
                logistics_status IN (
                                     'PENDING_SHIPMENT', -- 待发货
                                     'SHIPPED', -- 已发货
                                     'IN_TRANSIT', -- 运输中
                                     'TO_RECEIVE', -- 待收货
                                     'RECEIVED' -- 已收货
                    )
                );
    END IF;
END $$;

-- 取消或过期的候补允许重新登记，活跃候补仍保持唯一。
ALTER TABLE appointment_waitlist DROP CONSTRAINT IF EXISTS uk_waitlist_patient_slot;
CREATE UNIQUE INDEX IF NOT EXISTS uk_waitlist_patient_slot_active
    ON appointment_waitlist(patient_id, slot_id)
    WHERE deleted_at IS NULL AND status IN ('WAITING', 'NOTIFIED');

-- 活跃挂号订单不能重复占用同一号源快照。
CREATE UNIQUE INDEX IF NOT EXISTS uk_appointment_active_slot_snapshot
    ON appointment(slot_snapshot_id)
    WHERE deleted_at IS NULL AND status IN ('UNPAID', 'PAID', 'COMPLETED');

-- 有效家庭成员关系及默认就诊人唯一。
CREATE UNIQUE INDEX IF NOT EXISTS uk_patient_user_relation_active
    ON patient_user_relation(user_id, patient_id)
    WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_patient_user_relation_default
    ON patient_user_relation(user_id)
    WHERE deleted_at IS NULL AND is_default;

-- 每家医院只能有一个启用的默认药房。
CREATE UNIQUE INDEX IF NOT EXISTS uk_pharmacy_hospital_default
    ON pharmacy(hospital_id)
    WHERE deleted_at IS NULL AND status = 'ENABLED' AND is_default;

-- 支付渠道交易流水号在同一渠道内唯一，用于回调防重。
CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_order_provider_transaction
    ON payment_order(provider, provider_transaction_id)
    WHERE provider IS NOT NULL AND provider_transaction_id IS NOT NULL;

-- C端查询、超时任务与审计索引。
CREATE INDEX IF NOT EXISTS idx_triage_assessment_patient_created
    ON triage_assessment(patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_waitlist_slot_status
    ON appointment_waitlist(slot_id, status, queue_no);
CREATE INDEX IF NOT EXISTS idx_consultation_message_consult_time
    ON consultation_message(consult_id, created_at);
CREATE INDEX IF NOT EXISTS idx_drug_order_patient_created
    ON drug_order(patient_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_drug_order_expire
    ON drug_order(expire_at) WHERE status = 'PENDING_PAYMENT';
CREATE INDEX IF NOT EXISTS idx_drug_order_item_order
    ON drug_order_item(drug_order_id);
CREATE INDEX IF NOT EXISTS idx_drug_order_logistics_trace_order_time
    ON drug_order_logistics_trace(drug_order_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_report_patient_date
    ON patient_report(patient_id, report_date DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_report_indicator_report
    ON patient_report_indicator(report_id);
CREATE INDEX IF NOT EXISTS idx_medication_plan_patient_status
    ON medication_plan(patient_id, status, next_remind_at);
CREATE INDEX IF NOT EXISTS idx_follow_up_patient_status
    ON follow_up_plan(patient_id, status, due_at);
CREATE INDEX IF NOT EXISTS idx_notification_user_patient_created
    ON notification(user_id, patient_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_agent_tool_audit_user_created
    ON agent_tool_audit(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_tool_audit_session_created
    ON agent_tool_audit(session_id, created_at DESC);
