-- C端导诊规则与处方解读补充：在初始化脚本成功执行后运行，可重复执行。

-- 医院级导诊规则：按症状关键词推荐本院启用科室，不包含诊断或治疗结论。
CREATE TABLE IF NOT EXISTS triage_rule (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id bigint NOT NULL REFERENCES hospital(id),
    department_id bigint NOT NULL REFERENCES department(id),
    keyword varchar(128) NOT NULL,
    reason varchar(256) NOT NULL,
    urgency varchar(20) NOT NULL DEFAULT 'LOW',
    priority integer NOT NULL DEFAULT 100,
    status varchar(20) NOT NULL DEFAULT 'ENABLED',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT ck_triage_rule_urgency CHECK (urgency IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT ck_triage_rule_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_triage_rule_priority CHECK (priority >= 0)
);

-- 处方解读结果：由后续医生确认或解读生产链路写入，C端仅负责读取 READY 数据。
CREATE TABLE IF NOT EXISTS prescription_interpretation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id bigint NOT NULL REFERENCES prescription(id),
    content text,
    disclaimer varchar(500) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    generated_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT ck_prescription_interpretation_status CHECK (status IN ('PENDING', 'READY', 'FAILED'))
);

-- 同一处方仅保留一条有效解读记录，软删除历史记录不影响后续重生成。
CREATE UNIQUE INDEX IF NOT EXISTS uk_prescription_interpretation_active
    ON prescription_interpretation(prescription_id)
    WHERE deleted_at IS NULL;

-- 症状关键词匹配按医院和启用状态过滤，支持快速定位候选导诊规则。
CREATE INDEX IF NOT EXISTS idx_triage_rule_hospital_status_keyword
    ON triage_rule(hospital_id, status, keyword)
    WHERE deleted_at IS NULL;

-- C端按处方读取当前解读结果。
CREATE INDEX IF NOT EXISTS idx_prescription_interpretation_prescription_status
    ON prescription_interpretation(prescription_id, status)
    WHERE deleted_at IS NULL;
