-- C端当前登录账号收货地址簿；订单仍保存创建时的不可变地址快照。
CREATE TABLE IF NOT EXISTS c_user_delivery_address (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES c_user(id),
    receiver_name varchar(64) NOT NULL,
    receiver_phone varchar(32) NOT NULL,
    province varchar(20) NOT NULL,
    city varchar(64) NOT NULL,
    district varchar(64),
    detail_address varchar(200) NOT NULL,
    is_default boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT ck_c_user_delivery_address_province CHECK (province IN ('HENAN', 'SHANGHAI', 'BEIJING', 'JIANGSU', 'ZHEJIANG', 'GUANGDONG'))
);

-- 支持当前账号地址簿查询和默认地址排序。
CREATE INDEX IF NOT EXISTS idx_c_user_delivery_address_user_active
    ON c_user_delivery_address(user_id, is_default DESC, created_at ASC)
    WHERE deleted_at IS NULL;

-- 每个当前账号最多保留一个有效默认地址。
CREATE UNIQUE INDEX IF NOT EXISTS uk_c_user_delivery_address_default
    ON c_user_delivery_address(user_id)
    WHERE is_default = true AND deleted_at IS NULL;
